name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U app -d app_db"
          --health-interval=5s --health-timeout=5s --health-retries=10

    env:
      # Django settings envs (match your local .env / compose)
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app_db
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: "5432"
      SECRET_KEY: test-key
      DEBUG: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          ruff check .
          isort --check-only .
          black --check .

      - name: Migrate
        run: |
          python manage.py migrate --noinput

      - name: Tests (pytest + coverage)
        run: |
          pytest -q

      - name: Security audit (pip-audit)
        run: |
          pip-audit -r requirements.txt || true
